### ISSUE TITLE
iOS7 Support

### ISSUE THREAD

**Issue by SimonBackx** [yayscripting/smf-smartphone#11]
Als de website op iOS 7 wordt toegevoegd aan het startscherm, dan ontstaan volgende problemen:
- Zwarte tekst op zwarte achtergrond in de balk bovenaan. Fix door: 
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  (zou moeten werken, niet getest)
  ![image](https://f.cloud.github.com/assets/5277847/1891161/ba386128-7a38-11e3-9524-39d3d11f4048.png)
- Als de app wordt gesloten, dan behoud hij niet waarop hij zat. (dit is wrs niet op een eenvoudige manier te fixen, ligt aan ios)
- Op iOS ga je soms bij het typen van een bericht per ongeluk naar de vorige pagina omdat je op het pijltje naar de vorige pagina gaat. Dit is zeer ergerlijk en er zou een melding moeten komen als de pagina verlaten wordt als er een bericht/onderwerp ingevuld is.

**Comment by ghost** [comment]
> Als de app wordt gesloten, dan behoud hij niet waarop hij zat. (dit is wrs niet op een eenvoudige manier te fixen, ligt aan ios)

Helaas ligt dit inderdaad aan iOS. Denk dat het een wontfix is.

> Op iOS ga je soms bij het typen van een bericht per ongeluk naar de vorige pagina omdat je op het pijltje naar de vorige pagina gaat. Dit is zeer ergerlijk en er zou een melding moeten komen als de pagina verlaten wordt als er een bericht/onderwerp ingevuld is.

Kun je misschien een screenshot geven waar je per ongeluk op drukt?

**Comment by SimonBackx** [comment]
Een screenshot is niet echt nodig. In ios6 is het hetzelfde : http://i.msdn.microsoft.com/dynimg/IC587100.png
Er staat daar een terug knop van ios om naar de vorige pagina te gaan. Deze staat normaal nergens anders in de app, wel als je de website in de browser bekijkt natuurlijk. Eigenlijk een foutje in iOS. Dus je kan die knop volgens mij niet wegtoveren, een oplossing is dus gewoon om het verlaten van de pagina te blokkeren als er iets ingevuld is, en dat er dan een melding op komt: "bent u zeker dat u deze pagina wilt verlaten?". Dit is heel hard nodig.

**Comment by ghost** [comment]
Die "Previous" knop brengt je naar het vorige veld, niet de vorige pagina.
