### ISSUE TITLE
Terug naar startpagina

### ISSUE THREAD

**Issue by StefanJanssen95** [yayscripting/smf-smartphone#13]
Een knop om naar de startpagina van GMOT te gaan als je een bericht aan het schrijven bent, nu moet je 3 keer klikken voor je op de homepage bent...

**Comment by ericlegomeer** [comment]
Volgens mij is dit wat overdreven. 

Als je in een topic zit, heb je zowel boven als onder een Startpagina knop. Als je een bericht aan het schrijven bent, kun je die posten of de terug-toets (of terug knop onderaan [1]) gebruiken en dan ben je weer in het topic. Ergo, dan nog maar één klik verwijderd van de startpagina. 

Tijdens het plaatsen van een bericht, ben je dus twee kliks verwijderd van de startpagina en niet drie. Wat naar mijn idee zo gek niet is, want wie wil er tijdens het opstellen van een bericht ineens terug naar de startpagina? Dan heb je echt for no reason op de Antwoord knop gedrukt.

[1] Sinds #18 is toegevoegd, zit die knop natuurlijk belachelijk ver onderaan. Voor iOS gebruikers vast vervelend aangezien zij blijkbaar geen terugknop kennen (?) Gezien Simonke's issue #12
