### ISSUE TITLE
Klikken op titel van board of topic brengt je naar de desktop startpagina

### ISSUE THREAD

**Issue by StefanJanssen95** [yayscripting/smf-smartphone#15]
Klikken op titel van board of topic brengt je naar de desktop startpagina. Zegt denk ik genoeg met onderstaande afbeelding erbij :P 

http://gyazo.com/6a08ecf77596001fc004dc6afd8e78ee.png

Als je op de "Smartphone-GMOT (0.2.46)" klikt kom je op www.gmot.nl en niet op http://www.gmot.nl/index.php?topic=25508.0;smartphone

Dit probleem heb ik alleen op mijn Windows Phone 8 en niet op de desktop met de smartphone versie aan

**Comment by ghost** [comment]
Ik zie zo niet waar het probleem ligt. Zou je wellicht wat tests kunnen doen op andere platforms? Of op de native browser van je smartphone?

**Comment by ericlegomeer** [comment]
Na even gegoogled te hebben lijkt het een design 'feature' van Microsoft: 

If HREF is specified as a blank value (href="" or href=), executing the link might display the directory containing the current document, or it might generate an error, depending on other elements in the document and the server environment.
http://msdn.microsoft.com/en-us/library/ie/cc848861(v=vs.85).aspx

Aangezien de reloader JS functie al iedere keer gehangen wordt aan dit soort elementen, is het dan geen idee om JS te laten reloaden? Andere insteek is om letterlijk de url op te bouwen en te echoën, maar denk niet dat dat gewenst is. 

Ga het zelf momenteel even niet fixen, maar iemand anders kan het met deze informatie vast wel even in een pull verwerken :)! Alvast bedankt :D!

**Comment by ghost** [comment]
Het lijkt erop dat een href="." het probleem oplost. Op [deze](http://uploads.woutervdb.com/junkware/links-gmot/index.html) pagina kun je dat testen.

**Comment by ericlegomeer** [comment]
Als ik een href="." probeer op een eigen pagina (want de jouwe wil niet laden) dan ga ik zowel in Firefox, Chrome als Internet Explorer naar de root van de directory en refresht de pagina dus niet. 

Als dit is wat je bedoelt:

``` html
<!DOCTYPE html>
<html><body><a href=".">Punt</a>
```

Levert het hier in ieder geval niet het gewenste refresh gedrag op.

**Comment by ghost** [comment]
Je hebt gelijk; ik keek niet goed.
