### ISSUE TITLE
Deel van bericht word niet weergegeven.

### ISSUE THREAD

**Issue by StefanJanssen95** [yayscripting/smf-smartphone#16]
http://www.gmot.nl/index.php?topic=646.msg748414#msg748414
vs
http://www.gmot.nl/index.php?topic=646.msg748414#msg748414&smartphone

De smartphone versie laat een deel van mijn bericht weg. (2 regels tekst en een afbeelding). Ook na het legen van mijn cache is het er nog steeds niet.

**Comment by ericlegomeer** [comment]
Volgens mij komt dit door bug #7 dus lijkt me geen losse issue, maar misschien wel handige informatie voor het analyseren van bug #7 
De content die je mist, staat namelijk in de 'Afbeelding laden' knop:
![laadknop](https://f.cloud.github.com/assets/6524633/2025016/956c70d0-8872-11e3-8d69-2442f4718ac1.png)
En zodra je erop klikt, laadt de afbeelding en verdwijnt alle content die in de knop stond:
![laadknop2](https://f.cloud.github.com/assets/6524633/2025022/bc5ec9f4-8872-11e3-8653-a29976daad6b.png)
