### ISSUE TITLE
Tabel buiten scherm [Opera Mobile]

### ISSUE THREAD

**Issue by ericlegomeer** [yayscripting/smf-smartphone#21]
Op het moment dat de tabel breder is dan de post-div valt hij buiten het scherm en kan je niet scrollen

Ga bijvoorbeeld naar het WhatPulse topic.

Android 2.3 - Opara Mobile.

**Comment by ericlegomeer** [comment]
In Opera Mobile is het bij mijn gewoon prima horizontaal door te scrollen. Misschien was het probleem een Opera Mini probleem?

Horizontaal scrollen werkt inderdaad niet in Opera Mini, welke remote gerendered wordt. Echter, de layout gaat hier sowieso wel aardig in stuk:
![2014-03-12 15 12 13](https://f.cloud.github.com/assets/6524633/2397955/6895b3b0-a9f0-11e3-87e8-ddcf6f35c4ae.png)

In Opera Classic wordt de layout best oke geladen, maar werkt horizontaal scrollen ook niet. Hier wordt echter wel een scrollbalk aangeboden door de browser, welke prima functioneert:
![classic](https://f.cloud.github.com/assets/6524633/2398018/2691c8fe-a9f1-11e3-91cc-c52e0066ef53.png)

Ik denk dus dat hier verder niet meer naar gekeken hoeft te worden. Twee uit de drie geteste Opera browsers leveren gewoon de functionaliteit. De enige die faalde, faalde ook volledig op de rest van de layout en dan lijkt me de makkelijkste oplossing die browser niet te ondersteunen.

**Comment by yayscripting** [comment]
(Wontfix: close)
