### ISSUE TITLE
[leeg] en 7 gasten

### ISSUE THREAD

**Issue by Woutwo** [yayscripting/smf-smartphone#3]
Onderaan staat dat het forum bekeken wordt door niets en 7 gasten. Zie screenshot voor de duidelijkheid.

PS, het staat me bij dat iemand dit al eerder gemeld had, maar ik kon er hier geen melding over vinden. Tenzij ik er overheen gekeken heb

http://i.imgur.com/JBH5iNY.png

**Comment by ghost** [comment]
Bijzonder. [De code](https://github.com/yayscripting/smf-smartphone/blob/master/Themes/default/Wireless.template.php#L1059-L1079) checkt of "en" erbij moet staan, dus ik denk dat `num_users_online` niet klopt?
