### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by ericlegomeer** [yayscripting/smf-smartphone#31]
Polls moeten nog ingebouwd worden

**Comment by ericlegomeer** [comment]
Ik zie dat er al een groot deel van de poll code geschreven is. Kun je uitleggen wat er allemaal aan scheelde?

Het lijkt namelijk over het algemeen gewoon te functioneren (stemknop heb ik nog even toegevoegd voor het testen, conform de Verzend knop in action=post):
![poll](https://f.cloud.github.com/assets/6524633/2385427/a42cde0e-a91d-11e3-9cd3-ae6b7f3454df.png)
Het enige wat ik zie is dat de hoogte van de opties niet overeenkomt met de hoogte van alle andere elementen. Wat er dus ook voor zorgt dat ze niet helemaal mooi verticaal uitgelijnd zijn. Verder zijn de resultaatbalkjes van de poll nog niet geïmplementeerd, maar verder lijkt het oké, toch?

Note: Deze wordt niet door simplifybody gehaald en afbeeldingen in poll-opties worden dus automatisch geladen. Dit moet nog worden opgelost.

**Comment by yayscripting** [comment]
Geen flauw idee meer. Kan het zo zijn dat het resultaat nog mooie opmaak miste?

**Comment by ericlegomeer** [comment]
Mja, resultaatbalkjes misten nog en ik ben nog een beetje aan het prutsen met het kunnen verwijderen van een stem. Het lijkt bijna af, moet nog alleen een sexy balkje zien te bouwen, wat nog niet echt m'n sterkste punt is, maar zal even kijken wat ik er voor nu voor kan brouwen.
