### ISSUE TITLE
Automatische smartphone herkenning

### ISSUE THREAD

**Issue by ericlegomeer** [yayscripting/smf-smartphone#32]
Bij openen GMOT.nl automatisch de smartphone versie voorstellen / forceren

Ik zou gaan voor automatisch inschakelen, en onderaan een link naar de volledige versie, welke een cookie instelt (volledig=1 ofzo). Op de volledige versie onderaan ook weer een link naar de mobiele versie. Ik heb vaak op mobiele sites dat ze onvolledig zijn, en even voor iets wil switchen naar de volledige, maar dan ook weer terug wil naar de mobiele.

Voor deze cookie is (voor de wet) overigens geen toestemming nodig omdat het in dat geval noodzakelijk is voor het juist werken van de website.

**Comment by yayscripting** [comment]
Wanneer dit geïmplementeerd wordt lanceren we het als versie 1.0.

**Comment by yayscripting** [comment]
Ik stel voor het volgende te implementeren. Graag uw commentaar:
- Er wordt automatisch op basis van user agent smartphone gmot voorgeschoteld 
- Tenzij er een cookie is 
- Cookie wordt gecreëerd zodra je op 'Dekstopversie bekijken' klikt
- Onderaan normale website wordt ook een koppeling 'Smartphone GMOT' toegevoegd

Eventuele toevoegingen (waarvan ik voorstel deze niet direct te implementeren):
- Indien een bepaalde OS wordt gedetecteerd een melding weergeven met de mogelijkheden voor dit OS:
  - IOS: Eenmalig melding 'U kunt deze applicatie toevoegen aan uw startscherm'
  - WindowsPhone: U kunt een GMOT app downloaden in de app store
  - Android: U kunt een GMOT app downloaden in de app store

**Comment by ericlegomeer** [comment]
Wordt de cookie verwijderd/aangepast wanneer er onderaan de normale versie op 'smartphone gmot' wordt geklikt? 

Verder lijkt de opzet me prima.

De eventuele toevoegingen lijken me ook prima, maar ik zou dan wel bij allemaal een eenmalige melding willen zien. Als er namelijk toch al geïmplementeerd wordt voor iOS om een eenmalige melding te laten zien, dan lijkt me dat ook wel zo netjes voor de andere platformen.

**Comment by ericlegomeer** [comment]
Misschien trouwens ook een url optie inbouwen welke de meldingen tot het downloaden van apps en dergelijke uitschakelt. Dat is voor de 'app makers' wel handig lijkt me, want anders krijg je na het downloaden van de app de melding dat je de app kunt downloaden, sherlock :p 

Verder neem ik aan dat die webviews (?) die er gebruikt worden in de apps wel goed te herkennen zijn als Windows Phone en als Android. Mocht dit ergens toch lastig blijken, dan is een optie voor het forceren van de smartphone versie misschien ook wel een plezante oplossing voor de 'app makers'.
