### ISSUE TITLE
Lijsten werken niet juist (UBB)

### ISSUE THREAD

**Issue by ericlegomeer** [yayscripting/smf-smartphone#33]
[*] lijsten werken incorrect

**Comment by ericlegomeer** [comment]
Doordat _iemand_ op line 2116 in Subs.php gebruik maakt van:

``` php
if ($smileys !== false && $tag === null && ...
```

En de WIRELESS constante ervoor zorgt dat $smileys false wordt, is het een hel om dit te fixen. Dat if-statement is _blijkbaar_ verantwoordelijk voor het parsen van deze lists. Staat ook een comment boven:

``` php
// Item codes are complicated buggers... they are implicit [li]s and can make [list]s!
```

Ik zie niet helemaal in waarom het niet uitgevoerd mag worden wanneer $smileys false is. Misschien een doordenkfout van een developer welke dacht, van, in Wireless mode hebben ze geen smileys en hoeven ze ook deze lists niet!

De mogelijke oplossingen zijn:
- Het laten zitten, maar dat is vrij lelijk
- Subs.php aanpassen waarbij line 965 veranderd wordt van if (WIRELESS) naar if (WIRELESS && WIRELESS_PROTOCOL != 'smartphone'), wat de meest effectieve oplossing lijkt [1]
- Een eigen BBC parser schrijven hiervoor, maar zoals al uit de comment blijkt, wordt dat niet heel plezant
- De parser van SMF proberen te begrijpen en overnemen wat relevant is, maar dit is ook echt geen pretje (1.5kloc)
- De gehele parser overnemen in de smartphone template. Dan moet waarschijnlijk ook de prepareDisplayContext overgenomen worden, omdat die uiteindelijk de parse_bbc aanroept en het lijkt me niet praktisch als parse_bbc er twee keer overheen gaat. Dus dan ga je gewoon een deel van SMF dupliceren voor deze kleine feature.
- De wireless template omzetten naar een echt template, maar ik weet niet in hoeverre dat makkelijk zou kunnen en of die dan ook aan de hand van $_REQUEST['smartphone'] te enablen valt. En natuurlijk of er dan geen dingen gaan breken in het huidige thema.

[1] Hierbij moet wel worden opgelet dat de smileys dan geparset worden voordat de afbeeldingen gereplaced worden door de 'Afbeelding laden'-knoppen. Dus deze zouden dan via PHP of JS nog even ontknopt moeten worden.

**Comment by yayscripting** [comment]
Ik heb regel 2133 van Subs.php veranderd:

``` php
if ($smileys !== false && $tag === null && isset($itemcodes[substr($message, $pos + 1, 1)]) && substr($message, $pos + 2, 1) == ']' && !isset($disabled['list']) && !isset($disabled['li']))
```

naar

``` php
if (($smileys !== false || WIRELESS_PROTOCOL == 'smartphone') && $tag === null && isset($itemcodes[substr($message, $pos + 1, 1)]) && substr($message, $pos + 2, 1) == ']' && !isset($disabled['list']) && !isset($disabled['li']))
```

Jouw oplossing om `$smileys` op `true` te zetten werkte niet helemaal zoals verwacht. Smileys werden toen gezien als afbeeldingen.

**Comment by ericlegomeer** [comment]
Voor het op `true` zetten van `$smileys` had ik nog een voetnoot gemaakt dat dat inderdaad het probleem zou geven wat je nu omschrijft ;) Maar als de de fix die je nu hebt gedaan mooi werkt, dan is dat natuurlijk ook prima c:!
