### ISSUE TITLE
'Bekijk desktopsite' knop

### ISSUE THREAD

**Issue by JochemKuijpers** [yayscripting/smf-smartphone#39]
Ik denk dat het een nuttige toevoeging is als de smartphone versie een link naar de 'normale' website heeft. Ik kreeg een link doorgestuurd vanaf een telefoon, maar dan moet ik handmatig de URL aanpassen om op de desktop versie te komen - die een stuk makkelijker leest op een desktop.

**Comment by yayscripting** [comment]
Lijkt me inderdaad een goed idee :)
