### ISSUE TITLE
Classname forceDekstop typo

### ISSUE THREAD

**Issue by ericlegomeer** [yayscripting/smf-smartphone#54]
In de wireless template staat [hier](https://github.com/yayscripting/smf-smartphone/blob/master/Themes/default/Wireless.template.php#L1969): `class="forceDekstop"`. 

De hele class bestaat niet in de css file. Dus dit attribuut kan gewoon verwijderd worden volgens mij.

**Comment by yayscripting** [comment]
Nee joh!

https://github.com/yayscripting/smf-smartphone/blob/master/smartphone/mobile.js#L205-L210

**Comment by ericlegomeer** [comment]
Oké, hij wordt wel gebruikt, maar kan het dan op z'n minst 'Desktop' worden in plaats van 'Dekstop' :P? Want het ging eerder om de typo dan of het wel of niet gebruikt werd c:

**Comment by yayscripting** [comment]
Oh was me niet eens opgevallen, opgelost!
