### ISSUE TITLE
Waarschuwing posten alleen bij ingevuld bericht

### ISSUE THREAD

**Issue by ghost** [yayscripting/smf-smartphone#56]
Als je nu een antwoord wilt posten, maar dan alsnog het tabblad sluit (doe ik wel eens), krijg je alsnog een bericht. Ik als user hoef geen wijzigingen op te slaan die ik nooit heb gemaakt. Ik stel voor dat we een if/else toevoegen, bijvoorbeeld:

``` js
// ...
if (textarea.value !== '') {
  geefMelding();
}
```

**Comment by yayscripting** [comment]
Hoe dan? het beforeunload event is nogal een vreemd event :P.

Wat je dan moet doen is het event verwijderen.

``` javascript
window.removeEventListener("beforeunload", beforeUnload);
```

maar wanneer doe je dit dan?

**Comment by goldenice** [comment]
Waarom niet gewoon vlak voor de melding gegeven wordt? Je wrapt gewoon de inhoud van de 'beforeUnload' functie in de if die Wouter beschrijft. Dan hoef je helemaal geen events te (ont)koppelen en hoef je maar één if-clause toe te voegen.
